### ISSUE TITLE
Custom Media Queries

### ISSUE THREAD

**Issue by Spayco** [bolah2009/stylelint-disallow-bootstrap-properties#2]
as of now, this linter doesn't allow custom @media queries that Bootstrap doesn't support (https://getbootstrap.com/docs/5.0/layout/breakpoints/) to have CSS classes that would be disallowed.

**Comment by bolah2009** [comment]
Bootstrap only uses the following media query:

```css
@media (max-width: 575.98px) { ... }
@media (max-width: 767.98px) { ... }
@media (max-width: 991.98px) { ... }
@media (max-width: 1199.98px) { ... }
@media (max-width: 1399.98px) { ... }
```

There's 2 - 3 ways to approach this:
1. If the media `params` is exactly the same as bootstrap's, e.g. `(max-width: 575.98px)`, the linter disallow the CSS declaration, else it allows it.
2. If it uses max-width in the `params`, the linter disallows it, and suggest the user check for a suitable fit in the bootstrap breakpoint, else, it allows any other variant.

The API has access to the following attribute when parsing a CSS declaration (`decl`):

Example CSS:
```css
@media screen and (max-width: 576px) {
  .one {
    display: block !important;
  }
}
```

```js
// console.log(decl) from https://github.com/bolah2009/stylelint-disallow-bootstrap-properties/blob/7c6469f6e2ae84ec20d5b493edb00043af690b09/index.js#L24-L26

Declaration {
  raws: { before: '\n    ', between: ': ' },
  type: 'decl',
  parent: Rule {
    raws: { before: '\n  ', between: ' ', semicolon: true, after: '\n  ' },
    type: 'rule',
    nodes: [ [Circular] ],
    parent: AtRule {
      raws: [Object],
      type: 'atrule',
      name: 'media',
      parent: [Root],
      source: [Object],
      params: 'screen and (max-width: 576px)',
      nodes: [Array],
      lastEach: 5,
      indexes: [Object]
    },
    source: { start: [Object], input: [Input], end: [Object] },
    selector: '.one',
    lastEach: 5,
    indexes: { '5': 0 }
  },
  source: {
    start: { line: 3, column: 5 },
    input: Input {
      css: '@media screen and (max-width: 576px) {\n' +
        '  .one {\n' +
        '    display: block !important;\n' +
        '  }\n' +
        '}\n',
      hasBOM: false,
      file: '/Users/bola/project/forked-bootstrap-newsweek/css/style.css'
    },
    end: { line: 3, column: 30 }
  },
  prop: 'display',
  important: true,
  value: 'block'
}
```

From the `console.log(decl)`, we can see that `decl.parent.type` is 'atrule' and `decl.parent.name` is 'media', we can then check if any of the bootstrap media params matched `decl.parent.params`.


## Possible solution

1. Loop through every declaration parent, if the `decl.parent.type` is 'root' then we return, else if it is 'media' we check the `decl.parent.params` if it matches the bootstrap's, if it does we can disallow the property, else we ignore it
